package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldSpeed extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldSpeed</code>
	 */
	public MsoFldSpeed() { super(40043, 14); }

	/**
	 * Returns an instance of <code>MsoFldSpeed</code>
	 * @return An instance of <code>MsoFldSpeed</code>
	 */
	public static synchronized MsoFldSpeed getInst() { 
		if( me == null ) me = new MsoFldSpeed();
		return me;
	}
	private static MsoFldSpeed me;
}
