package customfields;

import com.portal.pcm.IntField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldFailedCount extends IntField {

	/**
	 * Constructs an instance of <code>MsoFldFailedCount</code>
	 */
	public MsoFldFailedCount() { super(41121, 1); }

	/**
	 * Returns an instance of <code>MsoFldFailedCount</code>
	 * @return An instance of <code>MsoFldFailedCount</code>
	 */
	public static synchronized MsoFldFailedCount getInst() { 
		if( me == null ) me = new MsoFldFailedCount();
		return me;
	}
	private static MsoFldFailedCount me;
}
