package customfields;

import com.portal.pcm.PoidField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldOrderObj extends PoidField {

	/**
	 * Constructs an instance of <code>MsoFldOrderObj</code>
	 */
	public MsoFldOrderObj() { super(42010, 7); }

	/**
	 * Returns an instance of <code>MsoFldOrderObj</code>
	 * @return An instance of <code>MsoFldOrderObj</code>
	 */
	public static synchronized MsoFldOrderObj getInst() { 
		if( me == null ) me = new MsoFldOrderObj();
		return me;
	}
	private static MsoFldOrderObj me;
}
