package customfields;

import com.portal.pcm.TStampField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldDepositDate extends TStampField {

	/**
	 * Constructs an instance of <code>MsoFldDepositDate</code>
	 */
	public MsoFldDepositDate() { super(43151, 8); }

	/**
	 * Returns an instance of <code>MsoFldDepositDate</code>
	 * @return An instance of <code>MsoFldDepositDate</code>
	 */
	public static synchronized MsoFldDepositDate getInst() { 
		if( me == null ) me = new MsoFldDepositDate();
		return me;
	}
	private static MsoFldDepositDate me;
}
