package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldPaymentType extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldPaymentType</code>
	 */
	public MsoFldPaymentType() { super(46010, 3); }

	/**
	 * Returns an instance of <code>MsoFldPaymentType</code>
	 * @return An instance of <code>MsoFldPaymentType</code>
	 */
	public static synchronized MsoFldPaymentType getInst() { 
		if( me == null ) me = new MsoFldPaymentType();
		return me;
	}
	private static MsoFldPaymentType me;
}
