package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldWelcomeCallStatus extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldWelcomeCallStatus</code>
	 */
	public MsoFldWelcomeCallStatus() { super(41140, 3); }

	/**
	 * Returns an instance of <code>MsoFldWelcomeCallStatus</code>
	 * @return An instance of <code>MsoFldWelcomeCallStatus</code>
	 */
	public static synchronized MsoFldWelcomeCallStatus getInst() { 
		if( me == null ) me = new MsoFldWelcomeCallStatus();
		return me;
	}
	private static MsoFldWelcomeCallStatus me;
}
