package customfields;

import com.portal.pcm.IntField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldAdhocDisc extends IntField {

	/**
	 * Constructs an instance of <code>MsoFldAdhocDisc</code>
	 */
	public MsoFldAdhocDisc() { super(43410, 1); }

	/**
	 * Returns an instance of <code>MsoFldAdhocDisc</code>
	 * @return An instance of <code>MsoFldAdhocDisc</code>
	 */
	public static synchronized MsoFldAdhocDisc getInst() { 
		if( me == null ) me = new MsoFldAdhocDisc();
		return me;
	}
	private static MsoFldAdhocDisc me;
}
