package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldEndStep extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldEndStep</code>
	 */
	public MsoFldEndStep() { super(43068, 3); }

	/**
	 * Returns an instance of <code>MsoFldEndStep</code>
	 * @return An instance of <code>MsoFldEndStep</code>
	 */
	public static synchronized MsoFldEndStep getInst() { 
		if( me == null ) me = new MsoFldEndStep();
		return me;
	}
	private static MsoFldEndStep me;
}
