package customfields;

import com.portal.pcm.TStampField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldToDate extends TStampField {

	/**
	 * Constructs an instance of <code>MsoFldToDate</code>
	 */
	public MsoFldToDate() { super(43409, 8); }

	/**
	 * Returns an instance of <code>MsoFldToDate</code>
	 * @return An instance of <code>MsoFldToDate</code>
	 */
	public static synchronized MsoFldToDate getInst() { 
		if( me == null ) me = new MsoFldToDate();
		return me;
	}
	private static MsoFldToDate me;
}
