package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldDiscountRate extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldDiscountRate</code>
	 */
	public MsoFldDiscountRate() { super(43417, 14); }

	/**
	 * Returns an instance of <code>MsoFldDiscountRate</code>
	 * @return An instance of <code>MsoFldDiscountRate</code>
	 */
	public static synchronized MsoFldDiscountRate getInst() { 
		if( me == null ) me = new MsoFldDiscountRate();
		return me;
	}
	private static MsoFldDiscountRate me;
}
