package customfields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldInstallationPlans extends SubStructField {

	/**
	 * Constructs an instance of <code>MsoFldInstallationPlans</code>
	 */
	public MsoFldInstallationPlans() { super(41143, 10); }

	/**
	 * Returns an instance of <code>MsoFldInstallationPlans</code>
	 * @return An instance of <code>MsoFldInstallationPlans</code>
	 */
	public static synchronized MsoFldInstallationPlans getInst() { 
		if( me == null ) me = new MsoFldInstallationPlans();
		return me;
	}
	private static MsoFldInstallationPlans me;
}
