package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldCommisionService extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldCommisionService</code>
	 */
	public MsoFldCommisionService() { super(41136, 3); }

	/**
	 * Returns an instance of <code>MsoFldCommisionService</code>
	 * @return An instance of <code>MsoFldCommisionService</code>
	 */
	public static synchronized MsoFldCommisionService getInst() { 
		if( me == null ) me = new MsoFldCommisionService();
		return me;
	}
	private static MsoFldCommisionService me;
}
