package customfields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldDepositNo extends StrField {

	/**
	 * Constructs an instance of <code>MsoFldDepositNo</code>
	 */
	public MsoFldDepositNo() { super(43152, 5); }

	/**
	 * Returns an instance of <code>MsoFldDepositNo</code>
	 * @return An instance of <code>MsoFldDepositNo</code>
	 */
	public static synchronized MsoFldDepositNo getInst() { 
		if( me == null ) me = new MsoFldDepositNo();
		return me;
	}
	private static MsoFldDepositNo me;
}
