package customfields;

import com.portal.pcm.TStampField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldPymtCollectionT extends TStampField {

	/**
	 * Constructs an instance of <code>MsoFldPymtCollectionT</code>
	 */
	public MsoFldPymtCollectionT() { super(43050, 8); }

	/**
	 * Returns an instance of <code>MsoFldPymtCollectionT</code>
	 * @return An instance of <code>MsoFldPymtCollectionT</code>
	 */
	public static synchronized MsoFldPymtCollectionT getInst() { 
		if( me == null ) me = new MsoFldPymtCollectionT();
		return me;
	}
	private static MsoFldPymtCollectionT me;
}
