package customfields;

import com.portal.pcm.ArrayField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldFupDowngrade extends ArrayField {

	/**
	 * Constructs an instance of <code>MsoFldFupDowngrade</code>
	 */
	public MsoFldFupDowngrade() { super(41224, 9); }

	/**
	 * Returns an instance of <code>MsoFldFupDowngrade</code>
	 * @return An instance of <code>MsoFldFupDowngrade</code>
	 */
	public static synchronized MsoFldFupDowngrade getInst() { 
		if( me == null ) me = new MsoFldFupDowngrade();
		return me;
	}
	private static MsoFldFupDowngrade me;
}
