package customfields;

import com.portal.pcm.IntField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldFupStatus extends IntField {

	/**
	 * Constructs an instance of <code>MsoFldFupStatus</code>
	 */
	public MsoFldFupStatus() { super(46012, 1); }

	/**
	 * Returns an instance of <code>MsoFldFupStatus</code>
	 * @return An instance of <code>MsoFldFupStatus</code>
	 */
	public static synchronized MsoFldFupStatus getInst() { 
		if( me == null ) me = new MsoFldFupStatus();
		return me;
	}
	private static MsoFldFupStatus me;
}
