package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldCommisionModel extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldCommisionModel</code>
	 */
	public MsoFldCommisionModel() { super(41135, 3); }

	/**
	 * Returns an instance of <code>MsoFldCommisionModel</code>
	 * @return An instance of <code>MsoFldCommisionModel</code>
	 */
	public static synchronized MsoFldCommisionModel getInst() { 
		if( me == null ) me = new MsoFldCommisionModel();
		return me;
	}
	private static MsoFldCommisionModel me;
}
