package customfields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldChargeHeadInfo extends SubStructField {

	/**
	 * Constructs an instance of <code>MsoFldChargeHeadInfo</code>
	 */
	public MsoFldChargeHeadInfo() { super(43324, 10); }

	/**
	 * Returns an instance of <code>MsoFldChargeHeadInfo</code>
	 * @return An instance of <code>MsoFldChargeHeadInfo</code>
	 */
	public static synchronized MsoFldChargeHeadInfo getInst() { 
		if( me == null ) me = new MsoFldChargeHeadInfo();
		return me;
	}
	private static MsoFldChargeHeadInfo me;
}
