package customfields;

import com.portal.pcm.IntField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldClientClassId extends IntField {

	/**
	 * Constructs an instance of <code>MsoFldClientClassId</code>
	 */
	public MsoFldClientClassId() { super(42115, 1); }

	/**
	 * Returns an instance of <code>MsoFldClientClassId</code>
	 * @return An instance of <code>MsoFldClientClassId</code>
	 */
	public static synchronized MsoFldClientClassId getInst() { 
		if( me == null ) me = new MsoFldClientClassId();
		return me;
	}
	private static MsoFldClientClassId me;
}
