package customfields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldEtZoneCode extends StrField {

	/**
	 * Constructs an instance of <code>MsoFldEtZoneCode</code>
	 */
	public MsoFldEtZoneCode() { super(43106, 5); }

	/**
	 * Returns an instance of <code>MsoFldEtZoneCode</code>
	 * @return An instance of <code>MsoFldEtZoneCode</code>
	 */
	public static synchronized MsoFldEtZoneCode getInst() { 
		if( me == null ) me = new MsoFldEtZoneCode();
		return me;
	}
	private static MsoFldEtZoneCode me;
}
