package customfields;

import com.portal.pcm.PoidField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldRefundRevEventObj extends PoidField {

	/**
	 * Constructs an instance of <code>MsoFldRefundRevEventObj</code>
	 */
	public MsoFldRefundRevEventObj() { super(42627, 7); }

	/**
	 * Returns an instance of <code>MsoFldRefundRevEventObj</code>
	 * @return An instance of <code>MsoFldRefundRevEventObj</code>
	 */
	public static synchronized MsoFldRefundRevEventObj getInst() { 
		if( me == null ) me = new MsoFldRefundRevEventObj();
		return me;
	}
	private static MsoFldRefundRevEventObj me;
}
