package customfields;

import com.portal.pcm.ArrayField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldDeposit extends ArrayField {

	/**
	 * Constructs an instance of <code>MsoFldDeposit</code>
	 */
	public MsoFldDeposit() { super(43069, 9); }

	/**
	 * Returns an instance of <code>MsoFldDeposit</code>
	 * @return An instance of <code>MsoFldDeposit</code>
	 */
	public static synchronized MsoFldDeposit getInst() { 
		if( me == null ) me = new MsoFldDeposit();
		return me;
	}
	private static MsoFldDeposit me;
}
