package customfields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldPlanInfo extends SubStructField {

	/**
	 * Constructs an instance of <code>MsoFldPlanInfo</code>
	 */
	public MsoFldPlanInfo() { super(43323, 10); }

	/**
	 * Returns an instance of <code>MsoFldPlanInfo</code>
	 * @return An instance of <code>MsoFldPlanInfo</code>
	 */
	public static synchronized MsoFldPlanInfo getInst() { 
		if( me == null ) me = new MsoFldPlanInfo();
		return me;
	}
	private static MsoFldPlanInfo me;
}
