package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldRate extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldRate</code>
	 */
	public MsoFldRate() { super(40033, 14); }

	/**
	 * Returns an instance of <code>MsoFldRate</code>
	 * @return An instance of <code>MsoFldRate</code>
	 */
	public static synchronized MsoFldRate getInst() { 
		if( me == null ) me = new MsoFldRate();
		return me;
	}
	private static MsoFldRate me;
}
