package customfields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldCatvInfo extends SubStructField {

	/**
	 * Constructs an instance of <code>MsoFldCatvInfo</code>
	 */
	public MsoFldCatvInfo() { super(40009, 10); }

	/**
	 * Returns an instance of <code>MsoFldCatvInfo</code>
	 * @return An instance of <code>MsoFldCatvInfo</code>
	 */
	public static synchronized MsoFldCatvInfo getInst() { 
		if( me == null ) me = new MsoFldCatvInfo();
		return me;
	}
	private static MsoFldCatvInfo me;
}
