package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldBytesUplinkBefFup extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldBytesUplinkBefFup</code>
	 */
	public MsoFldBytesUplinkBefFup() { super(46015, 14); }

	/**
	 * Returns an instance of <code>MsoFldBytesUplinkBefFup</code>
	 * @return An instance of <code>MsoFldBytesUplinkBefFup</code>
	 */
	public static synchronized MsoFldBytesUplinkBefFup getInst() { 
		if( me == null ) me = new MsoFldBytesUplinkBefFup();
		return me;
	}
	private static MsoFldBytesUplinkBefFup me;
}
