package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldStepValue extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldStepValue</code>
	 */
	public MsoFldStepValue() { super(43003, 14); }

	/**
	 * Returns an instance of <code>MsoFldStepValue</code>
	 * @return An instance of <code>MsoFldStepValue</code>
	 */
	public static synchronized MsoFldStepValue getInst() { 
		if( me == null ) me = new MsoFldStepValue();
		return me;
	}
	private static MsoFldStepValue me;
}
