package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:33 IST 2016
 * @author Autogenerated
 */


public class MsoFldPlanCategory extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldPlanCategory</code>
	 */
	public MsoFldPlanCategory() { super(43300, 3); }

	/**
	 * Returns an instance of <code>MsoFldPlanCategory</code>
	 * @return An instance of <code>MsoFldPlanCategory</code>
	 */
	public static synchronized MsoFldPlanCategory getInst() { 
		if( me == null ) me = new MsoFldPlanCategory();
		return me;
	}
	private static MsoFldPlanCategory me;
}
