package customfields;

import com.portal.pcm.TStampField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldCrAdjDate extends TStampField {

	/**
	 * Constructs an instance of <code>MsoFldCrAdjDate</code>
	 */
	public MsoFldCrAdjDate() { super(41129, 8); }

	/**
	 * Returns an instance of <code>MsoFldCrAdjDate</code>
	 * @return An instance of <code>MsoFldCrAdjDate</code>
	 */
	public static synchronized MsoFldCrAdjDate getInst() { 
		if( me == null ) me = new MsoFldCrAdjDate();
		return me;
	}
	private static MsoFldCrAdjDate me;
}
