package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldIdType extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldIdType</code>
	 */
	public MsoFldIdType() { super(40016, 3); }

	/**
	 * Returns an instance of <code>MsoFldIdType</code>
	 * @return An instance of <code>MsoFldIdType</code>
	 */
	public static synchronized MsoFldIdType getInst() { 
		if( me == null ) me = new MsoFldIdType();
		return me;
	}
	private static MsoFldIdType me;
}
