package customfields;

import com.portal.pcm.EnumField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldIstalFlag extends EnumField {

	/**
	 * Constructs an instance of <code>MsoFldIstalFlag</code>
	 */
	public MsoFldIstalFlag() { super(41109, 3); }

	/**
	 * Returns an instance of <code>MsoFldIstalFlag</code>
	 * @return An instance of <code>MsoFldIstalFlag</code>
	 */
	public static synchronized MsoFldIstalFlag getInst() { 
		if( me == null ) me = new MsoFldIstalFlag();
		return me;
	}
	private static MsoFldIstalFlag me;
}
