package customfields;

import com.portal.pcm.SubStructField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldOrgStructure extends SubStructField {

	/**
	 * Constructs an instance of <code>MsoFldOrgStructure</code>
	 */
	public MsoFldOrgStructure() { super(40081, 10); }

	/**
	 * Returns an instance of <code>MsoFldOrgStructure</code>
	 * @return An instance of <code>MsoFldOrgStructure</code>
	 */
	public static synchronized MsoFldOrgStructure getInst() { 
		if( me == null ) me = new MsoFldOrgStructure();
		return me;
	}
	private static MsoFldOrgStructure me;
}
