package customfields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldIpMaskValue extends StrField {

	/**
	 * Constructs an instance of <code>MsoFldIpMaskValue</code>
	 */
	public MsoFldIpMaskValue() { super(42207, 5); }

	/**
	 * Returns an instance of <code>MsoFldIpMaskValue</code>
	 * @return An instance of <code>MsoFldIpMaskValue</code>
	 */
	public static synchronized MsoFldIpMaskValue getInst() { 
		if( me == null ) me = new MsoFldIpMaskValue();
		return me;
	}
	private static MsoFldIpMaskValue me;
}
