package customfields;

import com.portal.pcm.DecimalField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Tue Oct 25 11:04:32 IST 2016
 * @author Autogenerated
 */


public class MsoFldCrAdjAmount extends DecimalField {

	/**
	 * Constructs an instance of <code>MsoFldCrAdjAmount</code>
	 */
	public MsoFldCrAdjAmount() { super(41127, 14); }

	/**
	 * Returns an instance of <code>MsoFldCrAdjAmount</code>
	 * @return An instance of <code>MsoFldCrAdjAmount</code>
	 */
	public static synchronized MsoFldCrAdjAmount getInst() { 
		if( me == null ) me = new MsoFldCrAdjAmount();
		return me;
	}
	private static MsoFldCrAdjAmount me;
}
