pin_deploy class -mnscp /config/device_state/ip  >   config.device_state.ip.podl
pin_deploy class -mnscp /config/device_state/ip/framed  >   config.device_state.ip.framed.podl
pin_deploy class -mnscp /config/device_state/ip/static  >   config.device_state.ip.static.podl
pin_deploy class -mnscp /config/device_state/mc  >   config.device_state.mc.podl
pin_deploy class -mnscp /config/device_state/modem  >   config.device_state.modem.podl
pin_deploy class -mnscp /config/device_state/nat  >   config.device_state.nat.podl
pin_deploy class -mnscp /config/device_state/router  >   config.device_state.router.podl
pin_deploy class -mnscp /config/device_state/router/cable  >   config.device_state.router.cable.podl
pin_deploy class -mnscp /config/device_state/router/wifi  >   config.device_state.router.wifi.podl
pin_deploy class -mnscp /config/device_state/stb  >   config.device_state.stb.podl
pin_deploy class -mnscp /config/device_state/vc  >   config.device_state.vc.podl
pin_deploy class -mnscp /config/device_state/voucher  >   config.device_state.voucher.podl
pin_deploy class -mnscp /config/distribution  >   config.distribution.podl
pin_deploy class -mnscp /config/lifecycle_states  >   config.lifecycle_states.podl
pin_deploy class -mnscp /config/telco/broadband  >   config.telco.broadband.podl
pin_deploy class -mnscp /device/ip  >   device.ip.podl
pin_deploy class -mnscp /device/ip/framed  >   device.ip.framed.podl
pin_deploy class -mnscp /device/ip/static  >   device.ip.static.podl
pin_deploy class -mnscp /device/modem  >   device.modem.podl
pin_deploy class -mnscp /device/nat  >   device.nat.podl
pin_deploy class -mnscp /device/router  >   device.router.podl
pin_deploy class -mnscp /device/router/cable  >   device.router.cable.podl
pin_deploy class -mnscp /device/router/wifi  >   device.router.wifi.podl
pin_deploy class -mnscp /device/stb  >   device.stb.podl
pin_deploy class -mnscp /device/vc  >   device.vc.podl
pin_deploy class -mnscp /device/voucher  >   device.voucher.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle  >   event.activity.mso_lifecycle.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/adjustment  >   event.activity.mso_lifecycle.adjustment.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/credit_debit_note  >   event.activity.mso_lifecycle.credit_debit_note.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/deposit  >   event.activity.mso_lifecycle.deposit.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/dispute  >   event.activity.mso_lifecycle.dispute.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/payment  >   event.activity.mso_lifecycle.payment.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/payment_reversal  >   event.activity.mso_lifecycle.payment_reversal.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/refund  >   event.activity.mso_lifecycle.refund.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/refund_reversal  >   event.activity.mso_lifecycle.refund_reversal.podl
pin_deploy class -mnscp /event/activity/mso_lifecycle/settlement  >   event.activity.mso_lifecycle.settlement.podl
pin_deploy class -mnscp /event/activity/reg  >   event.activity.reg.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear/monthly_mso_sb_pkg_dpop  >   event.billing.product.fee.cycle.cycle_arrear.monthly_mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_arrear.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_annual  >   event.billing.product.fee.cycle.cycle_arrear_annual.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_annual/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_arrear_annual.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_bimonthly  >   event.billing.product.fee.cycle.cycle_arrear_bimonthly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_bimonthly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_arrear_bimonthly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly  >   event.billing.product.fee.cycle.cycle_arrear_monthly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_et  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_et.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_alc_fta  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_alc_fta.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_alc_paid  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_alc_paid.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_pkg_bst  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_pkg_bst.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_pkg_dpop  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_pkg_dprp  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_pkg_dprp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_monthly/mso_sb_pkg_dstp  >   event.billing.product.fee.cycle.cycle_arrear_monthly.mso_sb_pkg_dstp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_quarterly  >   event.billing.product.fee.cycle.cycle_arrear_quarterly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_quarterly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_arrear_quarterly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_semiannual  >   event.billing.product.fee.cycle.cycle_arrear_semiannual.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_semiannual/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_arrear_semiannual.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_yearly  >   event.billing.product.fee.cycle.cycle_arrear_yearly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_arrear_yearly/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_arrear_yearly.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual  >   event.billing.product.fee.cycle.cycle_forward_annual.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_sb_alc_fdp  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_sb_alc_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_sb_pkg_fdp  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_sb_pkg_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual/mso_sb_tod  >   event.billing.product.fee.cycle.cycle_forward_annual.mso_sb_tod.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_gr_dc2  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_gr_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_gr_dc3  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_gr_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_gr_norm  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_gr_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_annual_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_annual_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_et  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_et.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_gr_tod  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_gr_tod.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_alc_fdp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_alc_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_alc_fta  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_alc_fta.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_alc_paid  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_alc_paid.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_pkg_bst  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_pkg_bst.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_pkg_dpop  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_pkg_dprp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_pkg_dprp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_pkg_dstp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_pkg_dstp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_pkg_fdp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_pkg_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_sb_tod  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_sb_tod.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_ssp  >   event.billing.product.fee.cycle.cycle_forward_monthly.mso_ssp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_gr_dc2  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_gr_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_gr_dc3  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_gr_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_gr_norm  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_gr_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_monthly_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly  >   event.billing.product.fee.cycle.cycle_forward_quarterly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_sb_alc_fdp  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_sb_alc_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_sb_pkg_fdp  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_sb_pkg_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_sb_tod  >   event.billing.product.fee.cycle.cycle_forward_quarterly.mso_sb_tod.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_gr_dc2  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_gr_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_gr_dc3  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_gr_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_gr_norm  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_gr_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual  >   event.billing.product.fee.cycle.cycle_forward_semiannual.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc/cm  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc/cr  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc/nd  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc/wlnd  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/cm  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.cm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/cr  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.cr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/crsoho  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/dcm  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/huwr  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/nd  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.nd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/nwifi  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental/wlnd  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_sb_adn_normal  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_sb_adn_normal.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_sb_alc_fdp  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_sb_alc_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_sb_pkg_fdp  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_sb_pkg_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_sb_tod  >   event.billing.product.fee.cycle.cycle_forward_semiannual.mso_sb_tod.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_gr_dc2  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_gr_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_gr_dc3  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_gr_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_gr_norm  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_gr_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_grant  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_grant.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_sb_dc2  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_sb_dc2.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_sb_dc3  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_sb_dc3.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_sb_fib  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_sb_fib.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp/mso_sb_norm  >   event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.mso_sb_norm.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_weekly  >   event.billing.product.fee.cycle.cycle_forward_weekly.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/cycle_forward_weekly/mso_sb_adn_fdp  >   event.billing.product.fee.cycle.cycle_forward_weekly.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /event/billing/product/fee/cycle/mso_grant  >   event.billing.product.fee.cycle.mso_grant.podl
pin_deploy class -mnscp /event/mso_et  >   event.mso_et.podl
pin_deploy class -mnscp /invoice/trial_billnow  >   invoice.trial_billnow.podl
pin_deploy class -mnscp /invoice_detail  >   invoice_detail.podl
pin_deploy class -mnscp /item/Education_Cess  >   item.Education_Cess.podl
pin_deploy class -mnscp /item/Entertainment_Tax  >   item.Entertainment_Tax.podl
pin_deploy class -mnscp /item/HW_Education_Cess  >   item.HW_Education_Cess.podl
pin_deploy class -mnscp /item/HW_Secondary_Higher_Education_Cess  >   item.HW_Secondary_Higher_Education_Cess.podl
pin_deploy class -mnscp /item/HW_Service_Tax  >   item.HW_Service_Tax.podl
pin_deploy class -mnscp /item/MSO_Tax  >   item.MSO_Tax.podl
pin_deploy class -mnscp /item/Secondary_Higher_Education_Cess  >   item.Secondary_Higher_Education_Cess.podl
pin_deploy class -mnscp /item/Service_Tax  >   item.Service_Tax.podl
pin_deploy class -mnscp /item/VAT  >   item.VAT.podl
pin_deploy class -mnscp /item/adjustment  >   item.adjustment.podl
pin_deploy class -mnscp /item/cycle_arrear/monthly_mso_sb_pkg_dpop  >   item.cycle_arrear.monthly_mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_et  >   item.cycle_arrear.mso_et.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_hw_amc  >   item.cycle_arrear.mso_hw_amc.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_hw_rental  >   item.cycle_arrear.mso_hw_rental.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_adn_normal  >   item.cycle_arrear.mso_sb_adn_normal.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_alc_fta  >   item.cycle_arrear.mso_sb_alc_fta.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_alc_paid  >   item.cycle_arrear.mso_sb_alc_paid.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_onetime_hw  >   item.cycle_arrear.mso_sb_onetime_hw.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_onetime_srvc  >   item.cycle_arrear.mso_sb_onetime_srvc.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_pkg_bst  >   item.cycle_arrear.mso_sb_pkg_bst.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_pkg_dpop  >   item.cycle_arrear.mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_pkg_dprp  >   item.cycle_arrear.mso_sb_pkg_dprp.podl
pin_deploy class -mnscp /item/cycle_arrear/mso_sb_pkg_dstp  >   item.cycle_arrear.mso_sb_pkg_dstp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_et  >   item.cycle_forward.mso_et.podl
pin_deploy class -mnscp /item/cycle_forward/mso_grant  >   item.cycle_forward.mso_grant.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_amc  >   item.cycle_forward.mso_hw_amc.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_amc/cm  >   item.cycle_forward.mso_hw_amc.cm.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_amc/cr  >   item.cycle_forward.mso_hw_amc.cr.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_amc/nd  >   item.cycle_forward.mso_hw_amc.nd.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_amc/wlnd  >   item.cycle_forward.mso_hw_amc.wlnd.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental  >   item.cycle_forward.mso_hw_rental.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/cm  >   item.cycle_forward.mso_hw_rental.cm.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/cr  >   item.cycle_forward.mso_hw_rental.cr.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/crsoho  >   item.cycle_forward.mso_hw_rental.crsoho.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/dcm  >   item.cycle_forward.mso_hw_rental.dcm.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/huwr  >   item.cycle_forward.mso_hw_rental.huwr.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/nd  >   item.cycle_forward.mso_hw_rental.nd.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/nwifi  >   item.cycle_forward.mso_hw_rental.nwifi.podl
pin_deploy class -mnscp /item/cycle_forward/mso_hw_rental/wlnd  >   item.cycle_forward.mso_hw_rental.wlnd.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_adn_fdp  >   item.cycle_forward.mso_sb_adn_fdp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_adn_normal  >   item.cycle_forward.mso_sb_adn_normal.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_alc_fdp  >   item.cycle_forward.mso_sb_alc_fdp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_alc_fta  >   item.cycle_forward.mso_sb_alc_fta.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_alc_paid  >   item.cycle_forward.mso_sb_alc_paid.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2  >   item.cycle_forward.mso_sb_dc2.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2/annual  >   item.cycle_forward.mso_sb_dc2.annual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2/monthly  >   item.cycle_forward.mso_sb_dc2.monthly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2/quarterly  >   item.cycle_forward.mso_sb_dc2.quarterly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2/semiannual  >   item.cycle_forward.mso_sb_dc2.semiannual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc2_postpaid  >   item.cycle_forward.mso_sb_dc2_postpaid.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3  >   item.cycle_forward.mso_sb_dc3.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3/annual  >   item.cycle_forward.mso_sb_dc3.annual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3/monthly  >   item.cycle_forward.mso_sb_dc3.monthly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3/quarterly  >   item.cycle_forward.mso_sb_dc3.quarterly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3/semiannual  >   item.cycle_forward.mso_sb_dc3.semiannual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_dc3_postpaid  >   item.cycle_forward.mso_sb_dc3_postpaid.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib  >   item.cycle_forward.mso_sb_fib.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib/annual  >   item.cycle_forward.mso_sb_fib.annual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib/monthly  >   item.cycle_forward.mso_sb_fib.monthly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib/quarterly  >   item.cycle_forward.mso_sb_fib.quarterly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib/semiannual  >   item.cycle_forward.mso_sb_fib.semiannual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fib_postpaid  >   item.cycle_forward.mso_sb_fib_postpaid.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_fup_topup  >   item.cycle_forward.mso_sb_fup_topup.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm  >   item.cycle_forward.mso_sb_norm.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm/annual  >   item.cycle_forward.mso_sb_norm.annual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm/monthly  >   item.cycle_forward.mso_sb_norm.monthly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm/quarterly  >   item.cycle_forward.mso_sb_norm.quarterly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm/semiannual  >   item.cycle_forward.mso_sb_norm.semiannual.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_norm_postpaid  >   item.cycle_forward.mso_sb_norm_postpaid.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_pkg_bst  >   item.cycle_forward.mso_sb_pkg_bst.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_pkg_dpop  >   item.cycle_forward.mso_sb_pkg_dpop.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_pkg_dprp  >   item.cycle_forward.mso_sb_pkg_dprp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_pkg_dstp  >   item.cycle_forward.mso_sb_pkg_dstp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_pkg_fdp  >   item.cycle_forward.mso_sb_pkg_fdp.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_tod  >   item.cycle_forward.mso_sb_tod.podl
pin_deploy class -mnscp /item/cycle_forward/mso_sb_tod/monthly  >   item.cycle_forward.mso_sb_tod.monthly.podl
pin_deploy class -mnscp /item/cycle_forward/mso_ssp_monthly  >   item.cycle_forward.mso_ssp_monthly.podl
pin_deploy class -mnscp /item/cycle_forward_arrear  >   item.cycle_forward_arrear.podl
pin_deploy class -mnscp /item/mso_cable_shift  >   item.mso_cable_shift.podl
pin_deploy class -mnscp /item/mso_catv_commitment  >   item.mso_catv_commitment.podl
pin_deploy class -mnscp /item/mso_commission_share  >   item.mso_commission_share.podl
pin_deploy class -mnscp /item/mso_cr_dr_note  >   item.mso_cr_dr_note.podl
pin_deploy class -mnscp /item/mso_deposit  >   item.mso_deposit.podl
pin_deploy class -mnscp /item/mso_domain_host  >   item.mso_domain_host.podl
pin_deploy class -mnscp /item/mso_email_addi  >   item.mso_email_addi.podl
pin_deploy class -mnscp /item/mso_et  >   item.mso_et.podl
pin_deploy class -mnscp /item/mso_hathway_share  >   item.mso_hathway_share.podl
pin_deploy class -mnscp /item/mso_hw_deposit  >   item.mso_hw_deposit.podl
pin_deploy class -mnscp /item/mso_hw_deposit/cm  >   item.mso_hw_deposit.cm.podl
pin_deploy class -mnscp /item/mso_hw_deposit/cr  >   item.mso_hw_deposit.cr.podl
pin_deploy class -mnscp /item/mso_hw_deposit/crsoho  >   item.mso_hw_deposit.crsoho.podl
pin_deploy class -mnscp /item/mso_hw_deposit/dcm  >   item.mso_hw_deposit.dcm.podl
pin_deploy class -mnscp /item/mso_hw_deposit/huwr  >   item.mso_hw_deposit.huwr.podl
pin_deploy class -mnscp /item/mso_hw_deposit/nd  >   item.mso_hw_deposit.nd.podl
pin_deploy class -mnscp /item/mso_hw_deposit/nwifi  >   item.mso_hw_deposit.nwifi.podl
pin_deploy class -mnscp /item/mso_hw_deposit/po  >   item.mso_hw_deposit.po.podl
pin_deploy class -mnscp /item/mso_hw_deposit/wlnd  >   item.mso_hw_deposit.wlnd.podl
pin_deploy class -mnscp /item/mso_hw_outright  >   item.mso_hw_outright.podl
pin_deploy class -mnscp /item/mso_hw_outright/cm  >   item.mso_hw_outright.cm.podl
pin_deploy class -mnscp /item/mso_hw_outright/cr  >   item.mso_hw_outright.cr.podl
pin_deploy class -mnscp /item/mso_hw_outright/crsoho  >   item.mso_hw_outright.crsoho.podl
pin_deploy class -mnscp /item/mso_hw_outright/dcm  >   item.mso_hw_outright.dcm.podl
pin_deploy class -mnscp /item/mso_hw_outright/huwr  >   item.mso_hw_outright.huwr.podl
pin_deploy class -mnscp /item/mso_hw_outright/nd  >   item.mso_hw_outright.nd.podl
pin_deploy class -mnscp /item/mso_hw_outright/nwifi  >   item.mso_hw_outright.nwifi.podl
pin_deploy class -mnscp /item/mso_hw_outright/wlnd  >   item.mso_hw_outright.wlnd.podl
pin_deploy class -mnscp /item/mso_installation  >   item.mso_installation.podl
pin_deploy class -mnscp /item/mso_installation/normal  >   item.mso_installation.normal.podl
pin_deploy class -mnscp /item/mso_installation/wireless  >   item.mso_installation.wireless.podl
pin_deploy class -mnscp /item/mso_ip_addi  >   item.mso_ip_addi.podl
pin_deploy class -mnscp /item/mso_late_fee  >   item.mso_late_fee.podl
pin_deploy class -mnscp /item/mso_penalty  >   item.mso_penalty.podl
pin_deploy class -mnscp /item/mso_penalty/bank  >   item.mso_penalty.bank.podl
pin_deploy class -mnscp /item/mso_purchase_adn_fdp  >   item.mso_purchase_adn_fdp.podl
pin_deploy class -mnscp /item/mso_purchase_atp  >   item.mso_purchase_atp.podl
pin_deploy class -mnscp /item/mso_purchase_outright  >   item.mso_purchase_outright.podl
pin_deploy class -mnscp /item/mso_refund  >   item.mso_refund.podl
pin_deploy class -mnscp /item/mso_refund_credit  >   item.mso_refund_credit.podl
pin_deploy class -mnscp /item/mso_refund_debit  >   item.mso_refund_debit.podl
pin_deploy class -mnscp /item/mso_space_addi  >   item.mso_space_addi.podl
pin_deploy class -mnscp /item/mso_usage  >   item.mso_usage.podl
pin_deploy class -mnscp /item/payment/mso_deposit  >   item.payment.mso_deposit.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit  >   item.payment.mso_hw_deposit.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/cm  >   item.payment.mso_hw_deposit.cm.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/cr  >   item.payment.mso_hw_deposit.cr.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/crsoho  >   item.payment.mso_hw_deposit.crsoho.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/dcm  >   item.payment.mso_hw_deposit.dcm.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/huwr  >   item.payment.mso_hw_deposit.huwr.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/nd  >   item.payment.mso_hw_deposit.nd.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/nwifi  >   item.payment.mso_hw_deposit.nwifi.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/po  >   item.payment.mso_hw_deposit.po.podl
pin_deploy class -mnscp /item/payment/mso_hw_deposit/wlnd  >   item.payment.mso_hw_deposit.wlnd.podl
pin_deploy class -mnscp /item/payment/reversal  >   item.payment.reversal.podl
pin_deploy class -mnscp /mso_aaa_suspended_bb_event  >   mso_aaa_suspended_bb_event.podl
pin_deploy class -mnscp /mso_account_balance  >   mso_account_balance.podl
pin_deploy class -mnscp /mso_ageing_data  >   mso_ageing_data.podl
pin_deploy class -mnscp /mso_ar_limit  >   mso_ar_limit.podl
pin_deploy class -mnscp /mso_bb_daily_usage  >   mso_bb_daily_usage.podl
pin_deploy class -mnscp /mso_bill_suppression_profile  >   mso_bill_suppression_profile.podl
pin_deploy class -mnscp /mso_catv_preactivated_svc  >   mso_catv_preactivated_svc.podl
pin_deploy class -mnscp /mso_cfg_amplifier_master  >   mso_cfg_amplifier_master.podl
pin_deploy class -mnscp /mso_cfg_bouquet_area_map  >   mso_cfg_bouquet_area_map.podl
pin_deploy class -mnscp /mso_cfg_bouquet_city_map  >   mso_cfg_bouquet_city_map.podl
pin_deploy class -mnscp /mso_cfg_catv_bcast_master  >   mso_cfg_catv_bcast_master.podl
pin_deploy class -mnscp /mso_cfg_catv_channel_master  >   mso_cfg_catv_channel_master.podl
pin_deploy class -mnscp /mso_cfg_catv_pt  >   mso_cfg_catv_pt.podl
pin_deploy class -mnscp /mso_cfg_catv_pt_channel_map  >   mso_cfg_catv_pt_channel_map.podl
pin_deploy class -mnscp /mso_cfg_city_tax_zones  >   mso_cfg_city_tax_zones.podl
pin_deploy class -mnscp /mso_cfg_client_class_type  >   mso_cfg_client_class_type.podl
pin_deploy class -mnscp /mso_cfg_cmts_cc_mapping  >   mso_cfg_cmts_cc_mapping.podl
pin_deploy class -mnscp /mso_cfg_cmts_master  >   mso_cfg_cmts_master.podl
pin_deploy class -mnscp /mso_cfg_credit_limit  >   mso_cfg_credit_limit.podl
pin_deploy class -mnscp /mso_cfg_ent_tax_states  >   mso_cfg_ent_tax_states.podl
pin_deploy class -mnscp /mso_cfg_et_mapping  >   mso_cfg_et_mapping.podl
pin_deploy class -mnscp /mso_cfg_inv_tmpl_ver  >   mso_cfg_inv_tmpl_ver.podl
pin_deploy class -mnscp /mso_cfg_node_master  >   mso_cfg_node_master.podl
pin_deploy class -mnscp /mso_cfg_pymt_priority  >   mso_cfg_pymt_priority.podl
pin_deploy class -mnscp /mso_cfg_refund_rule  >   mso_cfg_refund_rule.podl
pin_deploy class -mnscp /mso_cfg_state_tax_zones  >   mso_cfg_state_tax_zones.podl
pin_deploy class -mnscp /mso_cfg_subscriber_type  >   mso_cfg_subscriber_type.podl
pin_deploy class -mnscp /mso_cfg_subscriber_type/bb  >   mso_cfg_subscriber_type.bb.podl
pin_deploy class -mnscp /mso_cfg_subscriber_type/catv  >   mso_cfg_subscriber_type.catv.podl
pin_deploy class -mnscp /mso_cfg_vat_mapping  >   mso_cfg_vat_mapping.podl
pin_deploy class -mnscp /mso_config_acct_nameinfo  >   mso_config_acct_nameinfo.podl
pin_deploy class -mnscp /mso_config_bb_pt  >   mso_config_bb_pt.podl
pin_deploy class -mnscp /mso_config_cin  >   mso_config_cin.podl
pin_deploy class -mnscp /mso_contact_history  >   mso_contact_history.podl
pin_deploy class -mnscp /mso_cr_dr_note  >   mso_cr_dr_note.podl
pin_deploy class -mnscp /mso_customer_credential  >   mso_customer_credential.podl
pin_deploy class -mnscp /mso_deposit  >   mso_deposit.podl
pin_deploy class -mnscp /mso_device  >   mso_device.podl
pin_deploy class -mnscp /mso_device_order  >   mso_device_order.podl
pin_deploy class -mnscp /mso_et_charge_details  >   mso_et_charge_details.podl
pin_deploy class -mnscp /mso_inv_doc_reference  >   mso_inv_doc_reference.podl
pin_deploy class -mnscp /mso_ip_order  >   mso_ip_order.podl
pin_deploy class -mnscp /mso_last_session_detail  >   mso_last_session_detail.podl
pin_deploy class -mnscp /mso_lco_agreement  >   mso_lco_agreement.podl
pin_deploy class -mnscp /mso_lco_autopay_master  >   mso_lco_autopay_master.podl
pin_deploy class -mnscp /mso_lco_blk_payment  >   mso_lco_blk_payment.podl
pin_deploy class -mnscp /mso_lco_comm_process_failure  >   mso_lco_comm_process_failure.podl
pin_deploy class -mnscp /mso_lco_payment  >   mso_lco_payment.podl
pin_deploy class -mnscp /mso_lco_settlement_charges  >   mso_lco_settlement_charges.podl
pin_deploy class -mnscp /mso_lco_settlement_report  >   mso_lco_settlement_report.podl
pin_deploy class -mnscp /mso_lifecycle  >   mso_lifecycle.podl
pin_deploy class -mnscp /mso_lifecycle/device  >   mso_lifecycle.device.podl
pin_deploy class -mnscp /mso_mta_job  >   mso_mta_job.podl
pin_deploy class -mnscp /mso_ntf_email  >   mso_ntf_email.podl
pin_deploy class -mnscp /mso_ntf_sms  >   mso_ntf_sms.podl
pin_deploy class -mnscp /mso_ntf_welcome  >   mso_ntf_welcome.podl
pin_deploy class -mnscp /mso_order  >   mso_order.podl
pin_deploy class -mnscp /mso_plans_activation  >   mso_plans_activation.podl
pin_deploy class -mnscp /mso_prov_bb_order  >   mso_prov_bb_order.podl
pin_deploy class -mnscp /mso_prov_order  >   mso_prov_order.podl
pin_deploy class -mnscp /mso_purchased_plan  >   mso_purchased_plan.podl
pin_deploy class -mnscp /mso_rate_plan_selector_details  >   mso_rate_plan_selector_details.podl
pin_deploy class -mnscp /mso_receipt  >   mso_receipt.podl
pin_deploy class -mnscp /mso_refund  >   mso_refund.podl
pin_deploy class -mnscp /mso_srvc_reactivation_fee  >   mso_srvc_reactivation_fee.podl
pin_deploy class -mnscp /mso_task  >   mso_task.podl
pin_deploy class -mnscp /mso_temp_cur_bal  >   mso_temp_cur_bal.podl
pin_deploy class -mnscp /mso_trial_report  >   mso_trial_report.podl
pin_deploy class -mnscp /payinfo/invoice  >   payinfo.invoice.podl
pin_deploy class -mnscp /profile/customer_care  >   profile.customer_care.podl
pin_deploy class -mnscp /profile/wholesale  >   profile.wholesale.podl
pin_deploy class -mnscp /service/catv  >   service.catv.podl
pin_deploy class -mnscp /service/telco/broadband  >   service.telco.broadband.podl
pin_deploy class -mnscp /mso_grv_upload > mso_grv_upload.podl

pin_deploy class -mnscp /event/billing/settlement/ws/outcollect > event.billing.settlement.ws.outcollect.podl
pin_deploy class -mnscp /event/billing/settlement/ws/outcollect/charge_head_based > event.billing.settlement.ws.outcollect.charge_head_based.podl
pin_deploy class -mnscp /event/billing/settlement/ws/outcollect/active_cust_count_based > event.billing.settlement.ws.outcollect.active_cust_count_based.podl
pin_deploy class -mnscp /event/billing/mso_cr_dr_note          > event.billing.mso_cr_dr_note.podl
pin_deploy class -mnscp /event/billing/mso_penalty             > event.billing.mso_penalty.podl
pin_deploy class -mnscp /event/billing/mso_refund_credit       > event.billing.mso_refund_credit.podl
pin_deploy class -mnscp /event/billing/mso_refund_debit        > event.billing.mso_refund_debit.podl
pin_deploy class -mnscp /event/billing/settlement/ws/incollect > event.billing.settlement.ws.incollect.podl
pin_deploy class -mnscp /event/session/telco/broadband         > event.session.telco.broadband.podl
pin_deploy class -mnscp /mso_config_network_info 	       > mso_config_network_info.podl
pin_deploy class -mnscp /service/settlement/ws                 > service.settlement.ws.podl
pin_deploy class -mnscp /service/settlement/ws/incollect       > service.settlement.ws.incollect.podl
pin_deploy class -mnscp /device  > device.podl
pin_deploy class -mnscp /account  > account.podl
pin_deploy class -mnscp /mso_comm_process_failure  >   mso_comm_process_failure.podl
pin_deploy class -mnscp /active_session/telco/broadband > active_session_telco_broadband.podl
pin_deploy class -mnscp /config/aaa/broadband > config_aaa_broadband.podl
