#!/bin/sh
#source .bash_profile
user="$1"
pass="$2"
SID="$3"
location="$4"
#rm $location/execution_logs
sqlplus -S $user/$pass@$SID <<EOF
set termout off
set feedback off
set echo off
set linesize 500
set pagesize 0
set newpage 0
SET SERVEROUTPUT ON SIZE UNLIMITED
spool $location/POSTB_PARTC_SP_DOM7_DEC_JAN18.csv_orig
select customer_id||','||agreement_no||','||bill_no||',"'||replace(name,',',' ')||'",'||entity_code||',"'||replace(entity_name,',',' ')||'",'||decoder||','||smartcard||',"'||replace(address,chr(10),'')||'",'||item_type||','||total||','||lco_margin||','||brr_charges||','||gst_on_brr||','||payable_to_hathway||','||city||','||bill_creation_date from POSTB_PARTC_SP_DOM7_DEC_JAN18 where item_type <> 'Entertainment Tax' order by entity_code,customer_id,agreement_no,item_type asc;
spool off;
exit;
EOF
