#!/bin/sh
#
#       @(#) $Id: stop_all.sh /cgbubrm_7.5.0.rwsmod/2 2012/06/14 02:25:14 ssajjans Exp $
#
# Copyright (c) 1996, 2012, Oracle and/or its affiliates. All rights reserved. 
#      
#       This material is the confidential property of Oracle Corporation or its
#       licensors and may be used, reproduced, stored or transmitted only in
#       accordance with a valid Oracle license or sublicense agreement.
#

VERSION=7.5
PATH=/usr/bin:/bin
sh stop_all_kali &
vm1=$?
if [ $vm1 -eq 0 ] ; then
echo "Success"
fi
exit $?
