cp /home/pin/opt/portal/7.5/mso/include/mso_errs.h /home/pin/opt/portal/7.5/mso/include/mso_errs.h.04122015
cp /home/pin/opt/portal/7.5/mso/include/mso_utils.h /home/pin/opt/portal/7.5/mso/include/mso_utils.h.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_rate_pol/fm_rate_pol_post_rating.c /home/pin/opt/portal/7.5/mso/source/sys/fm_rate_pol/fm_rate_pol_post_rating.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_rate_aaa/fm_mso_rate_aaa_rate_bb_event.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_rate_aaa/fm_mso_rate_aaa_rate_bb_event.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_prov/fm_mso_prov_create_bb_action.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_prov/fm_mso_prov_create_bb_action.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_add_plan.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_add_plan.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_change_plan.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_change_plan.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_modify_customer.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_modify_customer.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_terminate_service.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_terminate_service.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_search.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_search.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_get_customer_info.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_get_customer_info.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_register_customer.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_register_customer.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_activate_customer.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_cust/fm_mso_cust_activate_customer.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_integ/fm_mso_integ_create_job.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_integ/fm_mso_integ_create_job.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_ntf/fm_mso_ntf_create_email_notification.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_ntf/fm_mso_ntf_create_email_notification.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_subscription_pol/fm_subscription_pol_spec_cycle_fee_interval.c /home/pin/opt/portal/7.5/mso/source/sys/fm_subscription_pol/fm_subscription_pol_spec_cycle_fee_interval.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_subscription_pol/fm_subscription_pol_spec_cancel.c /home/pin/opt/portal/7.5/mso/source/sys/fm_subscription_pol/fm_subscription_pol_spec_cancel.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_inv_pol/fm_inv_pol_prep_invoice.c /home/pin/opt/portal/7.5/mso/source/sys/fm_inv_pol/fm_inv_pol_prep_invoice.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_bill_pol/fm_bill_pol_post_billing.c /home/pin/opt/portal/7.5/mso/source/sys/fm_bill_pol/fm_bill_pol_post_billing.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_bill_pol/fm_bill_pol_spec_future_cycle.c /home/pin/opt/portal/7.5/mso/source/sys/fm_bill_pol/fm_bill_pol_spec_future_cycle.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_pymt/fm_mso_pymt_reverse_payment.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_pymt/fm_mso_pymt_reverse_payment.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_pymt/fm_mso_pymt_blk_get_payments.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_pymt/fm_mso_pymt_blk_get_payments.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_pymt_pol/fm_pymt_pol_under_payment.c /home/pin/opt/portal/7.5/mso/source/sys/fm_pymt_pol/fm_pymt_pol_under_payment.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_utils/fm_mso_utils_common_functions.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_utils/fm_mso_utils_common_functions.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_utils/fm_mso_utils_lifecycle.c /home/pin/opt/portal/7.5/mso/source/sys/fm_mso_utils/fm_mso_utils_lifecycle.c.04122015
cp /home/pin/opt/portal/7.5/mso/source/sys/fm_collections_pol/fm_mso_collections_pol_apply_late_fees.c /home/pin/opt/portal/7.5/mso/source/sys/fm_collections_pol/fm_mso_collections_pol_apply_late_fees.c.04122015
cp /home/pin/opt/portal/7.5/mso/config/mso_pin_billing_segment.xml /home/pin/opt/portal/7.5/mso/config/mso_pin_billing_segment.xml.04122015
cp /home/pin/opt/portal/7.5/mso/config/pin_config_business_type /home/pin/opt/portal/7.5/mso/config/pin_config_business_type.04122015
cp /home/pin/opt/portal/7.5/mso/PODL/mso_refund.podl /home/pin/opt/portal/7.5/mso/PODL/mso_refund.podl.04122015
cp /home/pin/opt/portal/7.5/mso/PODL/mso_et_charge_details.podl /home/pin/opt/portal/7.5/mso/PODL/mso_et_charge_details.podl.04122015
