pin_deploy class -smncp /mso_task/location_update/ip > mso_task.location_update.ip.podl
pin_deploy class -smncp /event/billing/settlement/ws/dsa > event.billing.settlement.ws.dsa.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quarterly_fdp > event.billing.product.fee.cycle.cycle_forward_quarterly_fdp.podl
pin_deploy class -smncp /mso_mta_job/state_change > mso_mta_job.state_change.podl
pin_deploy class -smncp /mso_task/state_change/router > mso_task.state_change.router.podl
pin_deploy class -smncp /event/billing/settlement/ws/outcollect > event.billing.settlement.ws.outcollect.podl
pin_deploy class -smncp /mso_task/attribute_update/ip > mso_task.attribute_update.ip.podl
pin_deploy class -smncp /item/mso_hw_deposit > item.mso_hw_deposit.podl
pin_deploy class -smncp /mso_task/device/ip > mso_task.device.ip.podl
pin_deploy class -smncp /mso_mta_job/location_update/ip > mso_mta_job.location_update.ip.podl
pin_deploy class -smncp /mso_task/state_change/ip > mso_task.state_change.ip.podl
pin_deploy class -smncp /item/cycle_forward/mso_sb_dc2 > item.cycle_forward.mso_sb_dc2.podl
pin_deploy class -smncp /mso_mta_job/location_update/router > mso_mta_job.location_update.router.podl
pin_deploy class -smncp /mso_catv_preactivated_svc > mso_catv_preactivated_svc.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_annual_fdp > event.billing.product.fee.cycle.cycle_forward_annual_fdp.podl
pin_deploy class -smncp /mso_mta_job/device > mso_mta_job.device.podl
pin_deploy class -smncp /device/router > device.router.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quarterly > event.billing.product.fee.cycle.cycle_forward_quarterly.podl
pin_deploy class -smncp /mso_device > mso_device.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_rental.podl
pin_deploy class -smncp /mso_task/device/router > mso_task.device.router.podl
pin_deploy class -smncp /mso_task/attribute_update/router > mso_task.attribute_update.router.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_bimonthly_fdp > event.billing.product.fee.cycle.cycle_forward_bimonthly_fdp.podl
pin_deploy class -smncp /mso_config_bb_pt > mso_config_bb_pt.podl
pin_deploy class -smncp /mso_cfg_subscriber_type > mso_cfg_subscriber_type.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_quarterly > event.billing.product.fee.cycle.cycle_arrear_quarterly.podl
pin_deploy class -smncp /mso_task/state_change > mso_task.state_change.podl
pin_deploy class -smncp /event/billing/settlement/ws/dsa_commission > event.billing.settlement.ws.dsa_commission.podl
pin_deploy class -smncp /mso_task/location_update/router > mso_task.location_update.router.podl
pin_deploy class -smncp /mso_task > mso_task.podl
pin_deploy class -smncp /item/cycle_forward/mso_sb_fib > item.cycle_forward.mso_sb_fib.podl
pin_deploy class -smncp /mso_order > mso_order.podl
pin_deploy class -smncp /mso_task/attribute_update > mso_task.attribute_update.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_monthly > event.billing.product.fee.cycle.cycle_arrear_monthly.podl
pin_deploy class -smncp /service/settlement/ws/incollect > service.settlement.ws.incollect.podl
pin_deploy class -smncp /item/mso_dsa_commission > item.mso_dsa_commission.podl
pin_deploy class -smncp /payinfo/invoice > payinfo.invoice.podl
pin_deploy class -smncp /item/mso_hw_outright > item.mso_hw_outright.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_bimonthly > event.billing.product.fee.cycle.cycle_arrear_bimonthly.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_semiannual > event.billing.product.fee.cycle.cycle_arrear_semiannual.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quadmonthly > event.billing.product.fee.cycle.cycle_forward_quadmonthly.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_rental.podl
pin_deploy class -smncp /mso_config_network_info > mso_config_network_info.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_rental.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_rental.podl
pin_deploy class -smncp /mso_task/location_update > mso_task.location_update.podl
pin_deploy class -smncp /mso_mta_job/device/ip > mso_mta_job.device.ip.podl
pin_deploy class -smncp /device > device.podl
pin_deploy class -smncp /item/payment/mso_hw_deposit > item.payment.mso_hw_deposit.podl
pin_deploy class -smncp /mso_mta_job/attribute_update > mso_mta_job.attribute_update.podl
pin_deploy class -smncp /item/cycle_forward/mso_hw_rental > item.cycle_forward.mso_hw_rental.podl
pin_deploy class -smncp /mso_mta_job/attribute_update/ip > mso_mta_job.attribute_update.ip.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_monthly_fdp > event.billing.product.fee.cycle.cycle_forward_monthly_fdp.podl
pin_deploy class -smncp /mso_mta_job/attribute_update/router > mso_mta_job.attribute_update.router.podl
pin_deploy class -smncp /mso_mta_job/device/router > mso_mta_job.device.router.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_semiannual > event.billing.product.fee.cycle.cycle_forward_semiannual.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quarterly/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_quarterly.mso_hw_amc.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_bimonthly/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_bimonthly.mso_hw_amc.podl
pin_deploy class -smncp /mso_lifecycle > mso_lifecycle.podl
pin_deploy class -smncp /event/activity/mso_lifecycle > event.activity.mso_lifecycle.podl
pin_deploy class -smncp /mso_mta_job > mso_mta_job.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_amc.podl
pin_deploy class -smncp /mso_mta_job/state_change/ip > mso_mta_job.state_change.ip.podl
pin_deploy class -smncp /item/mso_penalty > item.mso_penalty.podl
pin_deploy class -smncp /config/device_state/router > config.device_state.router.podl
pin_deploy class -smncp /config/device_state/ip > config.device_state.ip.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quadmonthly_fdp > event.billing.product.fee.cycle.cycle_forward_quadmonthly_fdp.podl
pin_deploy class -smncp /mso_ip_order/ip > mso_ip_order.ip.podl
pin_deploy class -smncp /item/cycle_forward/mso_hw_amc > item.cycle_forward.mso_hw_amc.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_semiannual_fdp > event.billing.product.fee.cycle.cycle_forward_semiannual_fdp.podl
pin_deploy class -smncp /mso_dsa_comm_rpt > mso_dsa_comm_rpt.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_weekly > event.billing.product.fee.cycle.cycle_forward_weekly.podl
pin_deploy class -smncp /service/settlement/ws/outcollect > service.settlement.ws.outcollect.podl
pin_deploy class -smncp /service/settlement/ws > service.settlement.ws.podl
pin_deploy class -smncp /event/billing/settlement/ws/incollect > event.billing.settlement.ws.incollect.podl
pin_deploy class -smncp /mso_order/router > mso_order.router.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_quadmonthly/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_quadmonthly.mso_hw_amc.podl
pin_deploy class -smncp /item/cycle_forward/mso_sb_tod > item.cycle_forward.mso_sb_tod.podl
pin_deploy class -smncp /item/cycle_forward/mso_sb_dc3 > item.cycle_forward.mso_sb_dc3.podl
pin_deploy class -smncp /item/mso_installation > item.mso_installation.podl
pin_deploy class -smncp /device/ip > device.ip.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_annual > event.billing.product.fee.cycle.cycle_forward_annual.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_yearly > event.billing.product.fee.cycle.cycle_arrear_yearly.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_annual/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_annual.mso_hw_rental.podl
pin_deploy class -smncp /mso_mta_job/location_update > mso_mta_job.location_update.podl
pin_deploy class -smncp /mso_mta_job/state_change/router > mso_mta_job.state_change.router.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_arrear_annual > event.billing.product.fee.cycle.cycle_arrear_annual.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_bimonthly > event.billing.product.fee.cycle.cycle_forward_bimonthly.podl
pin_deploy class -smncp /mso_task/device > mso_task.device.podl
pin_deploy class -smncp /item/cycle_forward/mso_sb_norm > item.cycle_forward.mso_sb_norm.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_semiannual/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_semiannual.mso_hw_amc.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_rental > event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_rental.podl
pin_deploy class -smncp /mso_lco_settlement_report > mso_lco_settlement_report.podl
pin_deploy class -smncp /event/billing/product/fee/cycle/cycle_forward_monthly/mso_hw_amc > event.billing.product.fee.cycle.cycle_forward_monthly.mso_hw_amc.podl
