/*Wholesale LCO Commission Changes*/
#define ACTIVE_CUST_COUNT_BASED_COMMISSION  1
#define CHARGE_HEAD_BASED_COMMISSION  2
#define ACTIVE_SERV_COUNT_BASED_DSA_COMMISSION  100
#define ACTIVE_SUBSCRIBER_COUNT_BASED_DSA_COMMISSION  101

#define LCO_COMMISSION 1
#define DTR_COMMISSION 2
#define SDT_COMMISSION 3

#define FROM_LCO_BALANCE_BUCKET 1
#define FROM_LCO_COMMISSION_BUCKET 0
#define BALANCE_BUCKET "/service/settlement/ws/incollect"
#define COMMISSION_BUCKET "/service/settlement/ws/outcollect"

#define NO_AGREEMENT            0
#define PREPAID_GROSS_MODEL     1
#define PREPAID_NET_MODEL       2
#define POSTPAID_GROSS_MODEL    3
#define POSTPAID_NET_MODEL      4
#define POSTPAID_BB_MODEL       5

#define GROSS_AMT      0
#define HATHWAY_SHARE  1
#define LCO_SHARE      2
#define LCO_SHARE_TAX  3
#define LCO_TO_HW_SHARE 5

#define ADJ_NO_TAX 4
#define ADJ_PRG_NAME "LCO Commission Correction"
#define CURRENCY 356

/*: Error Codes*/
#define MSO_ERR_INVALID_TRANSFER_AMOUNT 	100001
#define MSO_ERR_LCO_NO_ACTIVE_AGREEMENT 	100002
#define MSO_ERR_LCO_COMMISSION_PROCESS_FAILED 	100003
#define MSO_ERR_LCO_INSUFFICIENT_BALANCE  	100004
#define MSO_ERR_LCO_CREDIT_LIMIT_EXCEEDED  	100005
#define MSO_ERR_INVALID_COMM_MDL_SERV 		100006
#define MSO_ERR_LCO_BAL_BUCKET_NOT_FOUND 	100007
#define MSO_ERR_LCO_COMM_BUCKET_NOT_FOUND 	100008
#define MSO_ERR_LCO_COMMISSION_FAILURE 		100009
#define MSO_ERR_LCO_CREDIT_LIMIT_NOT_SET 	100010
#define MSO_ERR_DTR_COMM_BUCKET_NOT_FOUND 	100011
#define MSO_ERR_DTR_NO_ACTIVE_AGREEMENT 	100012
#define MSO_ERR_DTR_COMMISSION_FAILURE 		100013
/*: Error Codes*/


/*Commission applicable for*/
#define LCO_ONLY  	 	0
#define SDT_ONLY  		1
#define DT_ONLY			2
#define LCO_AND_SDT		3
#define LCO_AND_DT		4
#define SDT_AND_DT		5
#define LCO_SDT_AND_DT		6
