#!/bin/sh

now=`date +%s`
log_file_name=`pwd`/pin_cycle_fees_cancel_$now.log
echo "This program is to run the pin_cycle_fees application for cancelling expired products" >> $log_file_name
echo "Program started at `date`" >> $log_file_name

echo " Application's console log " >> $log_file_name
echo "====================================================" >> $log_file_name
pin_cycle_fees -segment 101 -cancel -verbose >> $log_file_name
echo "====================================================" >> $log_file_name
echo " Application's console log ends" >> $log_file_name

echo "Program ended at `date`" >> $log_file_name

exit 0
